services:
  postgres:
    image: postgres:16
    container_name: london_bikepoint_postgres
    environment:
      POSTGRES_USER: bikepoint
      POSTGRES_PASSWORD: bikepoint
      POSTGRES_DB: bikepoint
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  superset:
      build:
        context: .
        dockerfile: Dockerfile.superset
      container_name: london_bikepoint_superset
      environment:
        SUPERSET_SECRET_KEY: "dev_secret_key"
      ports:
        - "8088:8088"
      depends_on:
        - postgres
      volumes:
        - superset_home:/app/superset_home
      command: >
        bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin || true &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
        "

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: london_bikepoint_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "dev_secret_key"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bikepoint
      DB_USER: bikepoint
      DB_PASSWORD: bikepoint
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./dbt/london_bikepoint:/opt/airflow/dbt/london_bikepoint
      - ./dbt/profiles:/home/airflow/.dbt
      - airflow_home:/opt/airflow
    command: >
      bash -c "
      airflow standalone
      "

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.2
    container_name: london_bikepoint_dbt
    depends_on:
      - postgres
    volumes:
      - ./dbt/london_bikepoint:/usr/app
      - ./dbt/profiles:/root/.dbt
    working_dir: /usr/app
    entrypoint: ["tail", "-f", "/dev/null"]
    
volumes:
  postgres_data:
  superset_home:
  airflow_home:
